<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Users
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Email</th>
                            <th>Verified</th>
                            <th>Admin</th>
                            <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach($this->users as $i => $user) { ?>
                            <tr>
                                <td> <?php echo $user->id ?> </td>
                                <td> <?php echo $user->email ?> </td>
                                <td>
                                    <?php if($user->verified) { ?>
                                        <span class="glyphicon glyphicon-ok" aria-hidden="true" ></span>
                                    <?php } else { ?>
                                        <span class="glyphicon glyphicon-minus"></span>
                                    <?php } ?>
                                </td>
                                <td>
                                    <?php echo $this->forms['mkUserForm'][$i] ?>
                                </td>
                                <td>
                                    <?php echo $this->forms['delUserForm'][$i] ?>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                    <a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'signup'), null, true) ?>" class="btn btn-default">Add New</a>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
        </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                MailSettings
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Host</th>
                            <th>Port</th>
                            <th>Security</th>
                            <th>Email</th>
                            <!--<th>Password</th>-->
                            <th>Default</th>
                            <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php foreach( $this->mailSettings as $i => $setting) { ?>
                                <tr>
                                    <td><a href = '<?php echo $this->url(array('controller' => 'mailsettings','action' => 'save', 'id' => $setting->id), null, true)?>'><?php echo $setting->id ?></a></td>
                                    <td><?php echo $setting->host ?></td>
                                    <td><?php echo $setting->port ?></td>
                                    <td><?php echo $setting->stype ?></td>
                                    <td><?php echo $setting->email ?></td>
                                    <!--<td><?php /*echo $setting->password */?></td>-->
                                    <td><?php echo $this->forms['defSettingForm'][$i] ?></td>
                                    <td><?php echo $this->forms['delSettingForm'][$i] ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                    <a href="<?php echo $this->url(array('controller' => 'mailsettings', 'action' => 'save'), null, true) ?>" class="btn btn-default">Add New</a>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Products
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Type</th>
                                <th>Price</th>
                                <th>File</th>
                                <th>Image</th>
                                <th>Description</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach($this->products as $i => $product) {
                            $editPath = $this->url(array('controller' => 'products','action' => 'save', 'id' => $product->id), null, true);
                            ?>
                            <tr>
                                <td>
                                    <a href='<?php echo $editPath?>'> <?php echo $product->id ?></a>
                                </td>
                                <td> <?php echo $product->name ?> </td>
                                <td> <?php echo $product->getCategoryName() ?> </td>
                                <td> <?php echo $product->currency ?></td>
                                <td> <a href="<?php echo RUPLOADS_DATA . '/' . $product->file; ?>" download> <?php echo $product->file ?> </a></td>
                                <td> <a href="<?php echo $editPath?>"><img width="150px" src = "<?php if ($product->image) echo RUPLOADS_IMAGES . '/' . $product->image; else echo IMAGE_NOT_FOUND ?>" ></a>  </td>
                                <td> <?php echo substr($product->description,0,20) ?></td>
                                <td>
                                    <?php echo $this->forms['delProductForm'][$i] ?>
                                </td>
                            </tr>
                        <?php } ?>

                        </tbody>
                    </table>
                    <a href="<?php echo $this->url(array('controller' => 'products', 'action' => 'save'), null, true) ?>" class="btn btn-default">Add New</a>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Orders
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive table-bordered">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>User ID</th>
                            <th>Transaction ID</th>
                            <th>State</th>
                            <th>User Email</th>
                            <th>Date Created</th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->orders as $i => $order) { ?>
                                <tr>
                                    <td><?php echo $order->id ?></td>
                                    <td><?php echo $order->getUserId() ?></td>
                                    <td><?php echo $order->getTransactionId() ?></td>
                                    <td id = "<?php echo 'stateId' . $order->id ?>"><?php echo $order->state ?></td>
                                    <td><?php echo $order->email ?></td>
                                    <td><?php echo $order->getCreateDate() ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                    <a class="btn btn-info" id = "upButton" onclick = "stupdate()">Update Order States</a>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Currencies
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Code</th>
                            <th>Rate</th>
                            <th>Defaut</th>
                            <th>Active</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach($this->currencies as $i => $currency) {
                                $editPath = $this->url(array('controller' => 'currencies','action' => 'save', 'id' => $currency->id), null, true);?>
                            <tr>
                                <td> <a href="<?php echo $editPath ?>"><?php echo $currency->id ?></a></td>
                                <td> <?php echo $currency->code ?> </td>
                                <td> <?php echo number_format($currency->rate, 4) ?></td>
                                <td>
                                    <?php if($currency->def) { ?>
                                        <span class="glyphicon glyphicon-ok" aria-hidden="true" ></span>
                                    <?php } else { ?>
                                        <span class="glyphicon glyphicon-minus"></span>
                                    <?php } ?>
                                </td>
                                <td>
                                    <?php if($currency->active) { ?>
                                        <span class="glyphicon glyphicon-ok" aria-hidden="true" ></span>
                                    <?php } else { ?>
                                        <span class="glyphicon glyphicon-minus"></span>
                                    <?php } ?>
                                </td>
                            </tr>
                        <?php } ?>

                        </tbody>
                    </table>
                    <a href="<?php echo $this->url(array('controller' => 'currencies', 'action' => 'save'), null, true) ?>" class="btn btn-default">Add New</a>
                    <a href="<?php echo $this->url(array('controller' => 'currencies', 'action' => 'updater'), null, true) ?>" class="btn btn-info">Update Rates</a>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Orders
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive table-bordered">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>User Id</th>
                            <th>State</th>
                            <th>User Email</th>
                            <th>Date Created</th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                    <a href="/orders/stupdate" class="btn btn-default">test update state</a>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>
<!-- /.row -->