<?php echo $this->doctype() ?>
<?php
    $shop = $login = $dashboard = $signup = '';
    $actionName =  Zend_Controller_Front::getInstance()->getRequest()->getActionName();
    switch ($actionName) {
        case 'shop' : $shop = 'active'; break;
        case 'dashboard' : $dashboard = 'active'; break;
        case 'login' : $login = 'active'; break;
        case 'signup' : $signup = 'active'; break;
    }
?>

<html lang="en">
<head>



    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Products Pilot</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Bootstrap Core CSS -->
    <!--<link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">-->

    <!-- Custom CSS -->
    <link href="/bootstrap/css/shop-homepage.css" rel="stylesheet">

    <link href="/css/my.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>


    </style>


</head>
<body>
<div class="container">

    <nav class="navbar navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Products-Pilot</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class=<?php echo $shop ?>><a href="<?php echo $this->url(array('controller'=>'products', 'action' => 'shop'), 'default', true) ?>">Shop<span class="sr-only">(current)</span></a></li>
                    <!--<li><a href="<?php /*echo $this->url(array('controller'=>'products', 'action' =>'viewall'), 'default', true) */?>">ViewAll Products <span class="sr-only">(current)</span></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>-->
                </ul>
                <!--<form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>-->
                <ul class="nav navbar-nav navbar-right">
                    <li class=<?php echo $login ?> ><?php echo $this->loggedInAs(); ?></li>
                    <li class=<?php echo $signup ?>><a href="<?php echo $this->url(array('controller'=>'auth', 'action' => 'signup'), 'default', true) ?>">SignUp</a></li>

                    <?php if($this->isAdmin()) { ?>
                        <li class=<?php echo $dashboard ?>><a href="<?php echo $this->url(array('controller'=>'users', 'action' => 'dashboard'), 'default', true) ?>">Dashboard</a></li>
                    <?php } ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">AccountSettings<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('controller'=>'auth', 'action' => 'chpass'), 'default', true) ?>">ChangePassword</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'auth', 'action' => 'logout'), 'default', true) ?>">LogOut</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</div>
<div class="container-fluid">


            <?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>

            <?php if ($flashMessenger->hasMessages('info')): ?>
                <div class='alert alert-info' style='margin-top:10px'>
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <?php foreach ($flashMessenger->getMessages('info') as $msg): ?>
                        <strong></strong> <?php echo $msg . "<br>" ?>
                    <?php endforeach; ?>
                </div>
            <?php $flashMessenger->clearMessages('info'); endif; ?>

            <?php if ($flashMessenger->hasMessages('success')): ?>
                <div class='alert alert-success' style='margin-top:10px'>
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <?php foreach ($flashMessenger->getMessages('success') as $msg): ?>
                        <strong></strong> <?php echo $msg . "<br>"  ?>
                    <?php endforeach; ?>
                </div>
            <?php $flashMessenger->clearMessages('success'); endif; ?>

            <?php if ($flashMessenger->hasMessages('error')): ?>
                <div class='alert alert-danger' style='margin-top:10px'>
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <?php foreach ($flashMessenger->getMessages('error') as $msg): ?>
                        <strong></strong> <?php echo $msg . "<br>"  ?>
                    <?php endforeach; ?>
                </div>
            <?php $flashMessenger->clearMessages('error'); endif;?>



            <?php echo $this->layout()->content ?>

</div>
<!-- /.container -->

<div class="container">

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Products-Pilot 2015</p>
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->

<!-- jQuery -->
<!--<script src="/bootstrap/js/jquery.js"></script>-->

<!-- Bootstrap Core JavaScript -->
<!--<script src="/bootstrap/js/bootstrap.min.js"></script>-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<?=$this->headScript();?>

</body>
</html>